fix: semver checking
coreruleset/crs-toolchain pull request #122
Opened 2024-03-01 14:21 UTC by fzipi

In some cases we need to use a "short version".

👉 This somehow got into a different PR, I'm raising it here so it is visible.

2024-03-01 15:21 UTC, fzipi commented
wth. pushed one additional commit, and it is not showing up 🤔

2024-03-02 07:24 UTC, theseion requested changes

2024-03-02 07:24 UTC, theseion commented on regex/definitions.go
> +// As numbers can grow to something like 10.12.123, the range is set to 3-8 to capture bigger numbers.
There's no range in the regex...?

2024-03-02 07:24 UTC, theseion commented on regex/definitions.go
> +// This regex is used to match the version in the setup file.
```suggestion
```

2024-03-02 07:24 UTC, theseion commented on regex/definitions.go
>  // The matched end year of the copyright year range will be captured in group 1.
In all the regular expressions below, the year / version is actually in capture group 2, not 1. Could you update the comments?

2024-03-02 13:47 UTC, fzipi commented on regex/definitions.go
> +// As numbers can grow to something like 10.12.123, the range is set to 3-8 to capture bigger numbers.
Yeah, I moved to `\d+`. Removing.

2024-03-02 14:06 UTC, theseion submitted a review, later dismissed

2024-03-02 14:06 UTC, theseion commented on regex/definitions.go
> +// Everything up to the value of the test title is captured in group 1, test title in group 2.
the title isn't captured.

2024-03-02 17:50 UTC, fzipi commented on regex/definitions.go
> +// Everything up to the value of the test title is captured in group 1, test title in group 2.
Now it is! 🥳

2024-03-02 20:44 UTC, theseion approved these changes

2024-03-02 20:44 UTC, merged